### ISSUE TITLE
[Question] signaling server for simple-peer and compare simple-signal and signalhub

### ISSUE THREAD

**Issue by pwFoo** [t-mullen/simple-signal#21]
Hi @t-mullen,
I found your simple-signal and the link to https://github.com/mafintosh/signalhub during searching for a offer/answer exchange method. 

I try to set up a simple signal / offer+answer exchange server (should run on simple webspace of possible or with a simple sef hosted service).

simple-signal and signalhub looks like nodejs server part? So requirements are the same I think, but which one is recommend? First look signalhub seems to be better for availability (supports more than one hub)?

Regards

Andre

**Comment by pwFoo** [comment]
signalhub looks nice, but last commit is two years ago...

**Comment by t-mullen** [comment]
`signalhub` is a general-purpose but signalling library that lets you broadcast messages over shared channels. It's not specific to WebRTC. It requires virtually no server-side code, meaning it's easy to setup but inflexible about how messages are delivered. 

`simple-signal` uses [socket.io](https://github.com/socketio/socket.io) as it's transport. It's a message-based protocol built on top of Websockets and HTTP (or HTTPS). It requires some custom server-side code - but you can do things you can't easily do with signalhub like:
- Only allowing peers to connect to a subset of other peers.
- Requiring peers to authenticate before connecting to a certain peer.
- Connecting peers in specific network architectures that would be difficult to do without a server.

Since `simple-signal` is built specifically for `simple-peer`, it abstracts away the signalling layer entirely, so you can just call `connect()` and `accept()` and be connected. You don't need to worry about things like SDP and trickle ICE and `signal` events. If you have advanced usecases, these things are still available to be tweaked.

Personally, I would recommend `simple-signal` if you're using `simple-peer` already. I'm probably biased though! 😄

**Comment by pwFoo** [comment]
ok, thank's, I#ll consider the additional information about integration and inflexible message delivery 👍
