### ISSUE TITLE
Add contributing guideline

### ISSUE THREAD

**Issue by d-asensio** [t-mullen/simple-signal#5]
Before submitting a PR it's very useful to have a contributing guideline, to answer questions like:
- Should I build the client and commit the minified file with my changes?

**Comment by t-mullen** [comment]
I'm not a huge fan of contributor guidelines when there's a small number of contributors. It can create a barrier of entry while only saving minimal time in discussions. (It's absolutely necessary for large projects with many contributors). I'd rather fix issues as they come instead of posting a long list of requirements for PRs that might scare away one-line bugfixes.

As for committing the minified file, I'd prefer to build it so I can be sure nothing else made it in (another reason it's a bad pattern, as you pointed out in #6).

**Comment by d-asensio** [comment]
I completely agree! Since I'll tackle the #6 issue ASAP and the proposal of writing a contributor guideline came from the confussion I had when I found the minified file under version control, I close the issue. 😄
